# experiment configs
seed: 42                            # Random seed.
use_gpu: True                       # Whether to use GPU or not.
jitting: True                       # Whether to run with jitting.

# training configs
training_steps: 1_000_000           # Total number of training steps.
eval_episodes: 50                   # Number of evaluation episodes.
evaluate_interval: 5000             # Number of timesteps between evaluations.
batch_size: 64                      # Size of the training batch.
