# experiment configs
seed: 42                            # Random seed.
use_gpu: True                       # Whether to use GPU or not.
jitting: True                       # Whether to run with jitting.

# training configs
training_steps: 1_000_000           # Total number of training steps.
eval_episodes: 50                   # Number of evaluation episodes.
evaluate_interval: 2000             # Number of timesteps between evaluations.

# optimizer configs
learning_rate: 0.0001               # Optimizer learning rate. 

# network configs
batch_size: 64                      # Size of the training batch.
replay_capacity: 20000              # Capacity of the replay buffer.
hidden_units: [64, 64]              # Number of network hidden units

# RL configs
target_period: 5000                 # How many timesteps to update the target net.
discount_factor: 0.99               # Q-learning discount factor.
epsilon_begin: 1.                   # Initial epsilon-greedy exploration.
epsilon_end: 0.05                   # Final epsilon-greedy exploration.
epsilon_steps: 100_000              # Steps over which to anneal epsilon.

# env configs
env: CartPole-v0                    # Name of the OpenAI Gym environment to use.
num_envs: 20                        # Number of environments to use.
